services:
  # 1. O ROTEADOR CENTRAL (Broker)
  integrador:
    build: ./integrador
    container_name: integrador_gateway
    ports:
      - "8080:8080/udp" # Escuta Sensores UDP (Temperatura)
      - "8081:8081/tcp" # Escuta Sensores TCP (NFC/Catraca)
      - "8082:8082/tcp" # Escuta Atuadores (Ar e Lâmpada)
      - "8083:8083/tcp" # Escuta Clientes (Dashboard/Controle)
    restart: always

  # 2. SENSORES
  sensor_temp_sala1:
    build: ./sensor_udp  
    container_name: sensor_temp_sala1
    depends_on:
      - integrador
    environment:
      - SERVER_ADDR=integrador:8080
      - SENSOR_ID=SALA_1
      - SENSOR_TIPO=T         
    restart: always

  sensor_nfc_entrada:
    build: ./sensor_tcp  
    container_name: sensor_nfc_entrada
    depends_on:
      - integrador
    environment:
      - SERVER_ADDR=integrador:8081
      - SENSOR_ID=CATRACA_ENTRADA
      - SENSOR_TIPO=NFC      
    restart: always

  # 3. ATUADORES
  atuador_ar_sala1:
    build: ./atuador_ac  
    container_name: atuador_ar_sala1
    depends_on:
      - integrador
    environment:
      - INTEGRADOR_ADDR=integrador:8082
      - ATUADOR_ID=SALA_1
      - ATUADOR_TIPO=AC       
    restart: always

  atuador_lampada_sala1:
    build: ./atuador_led 
    container_name: atuador_lampada_sala1
    depends_on:
      - integrador
    environment:
      - INTEGRADOR_ADDR=integrador:8082
      - ATUADOR_ID=SALA_1
      - ATUADOR_TIPO=LED      
    restart: always

  # 4. O CÉREBRO / DASHBOARD
  cliente:
    build: ./cliente
    container_name: cliente_dashboard
    depends_on:
      - integrador
    environment:
      - INTEGRADOR_ADDR=integrador:8083 
    stdin_open: true 
    tty: true
    