services:
  servidor:
    build: ./servidor
    container_name: servidor_ormuz
    environment:
      MEU_SETOR: SETOR_A
    ports:
      - "8080:8080/udp"
      - "8081:8081/tcp"
      - "8082:8082/tcp"
      - "8083:8083/tcp"
      - "8084:8084/tcp"
    restart: always

  dashboard:
    build: ./dashboard
    container_name: dashboard_operador
    depends_on:
      - servidor
    environment:
      SERVER_ADDR: servidor:8083
    stdin_open: true
    tty: true
    restart: always

  drone:
    build: ./drone
    container_name: drone_01
    depends_on:
      - servidor
    environment:
      SERVER_ADDR: servidor:8082
      DRONE_ID: DRONE_01
    restart: always

  radar_tcp:
    build: ./radar_tcp
    container_name: radar_tcp_01
    depends_on:
      - servidor
    environment:
      SERVER_ADDR: servidor:8081
      SENSOR_ID: RADAR_01
      SENSOR_TIPO: RADAR
    restart: always

  sensor_tlm:
    build: ./sensor_tlm
    container_name: sensor_tlm_01
    depends_on:
      - servidor
    environment:
      SERVER_ADDR: servidor:8080
      SENSOR_ID: BOIA_01
    restart: always
    